version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.8
    commands:
      - python -V
      - apt-get -q update
      - apt-get -q -y install jq
      - jq --version
      - pip -q install awscli
      - pip -q install aws-sam-cli
  build:
    commands:
      - pipenv run sam package --template-file template.yaml --s3-bucket pipeline-bucket-test-manpreet --output-template-file packaged-template.yaml
      # - ./test.sh
  # post_build:
  #   commands:
  #     - pipenv run sam package --template-file template.yaml --s3-bucket pipeline-bucket-test-manpreet --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml