version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
  build:
    commands:
      - pipenv run sam build
  post_build:
    commands:
      - pipenv run sam package --template-file template.yaml --s3-bucket pipeline-bucket-test-manpreet --output-template-file packaged-template.yaml
      - pipenv run sam deploy --template-file  packaged-template.yaml --region ap-south-1 --capabilities CAPABILITY_IAM --stack-name pipeline-auto
artifacts:
  files:
    - template.yaml
    - packaged-template.yaml